class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'SpecPass',
      'app_subtitle': 'Biometric Studio',
      'studio_tab': 'Studio',
      'standards_tab': 'Standards',
      'saved_tab': 'Saved',
      'guarantee_tab': 'Guarantee',
      'search_placeholder': 'Search 140+ countries & visa types...',
      'take_photo': 'Take Biometric Photo',
      'import_gallery': 'Import from Gallery',
      'camera_studio': 'Camera Studio',
      'baby_mode': 'Baby / Infant Mode',
      'baby_mode_desc': 'Relaxed ICAO 9303 rules for infants under 1 year',
      'compliance_inspection': 'Compliance Inspection',
      'biometric_compliant': 'Biometric Compliant',
      'original_shot': 'Original Shot',
      'background_presets': 'Background Color Presets',
      'matting_cleanse': 'Matting Cleanse Level',
      'balanced': 'Balanced',
      'deep_cleanse': 'Deep Cleanse (Wall Shadows)',
      'auto_enhance': 'Auto-Enhance Lighting',
      'brightness': 'Brightness',
      'contrast': 'Contrast',
      'export_sheet': 'Export 4×6" Print Sheet',
      'export_single': 'Export Single Digital Photo',
      'export_pdf': 'Export Printable PDF (A4 / 4×6")',
      'dm_guide_title': 'Print at dm / Rossmann in Germany (~0.27 €)',
      'dm_guide_step1': '1. At dm Fotoparadies kiosk select "Foto sofort drucken" ➔ 10×15 cm.',
      'dm_guide_step2': '2. Do NOT choose "Passfoto" (~7.95 €). Choose standard photo (~0.27 €).',
      'dm_guide_step3': '3. Select "Ohne Rand" (100% borderless scale). Cut with counter trimmer.',
      'family_sheet_title': 'Family Combo Sheet',
      'family_sheet_desc': 'Combine multiple family photos onto one 10×15 cm sheet',
    },
    'de': {
      'app_title': 'SpecPass',
      'app_subtitle': 'Biometrisches Studio',
      'studio_tab': 'Studio',
      'standards_tab': 'Standards',
      'saved_tab': 'Gespeichert',
      'guarantee_tab': 'Garantie',
      'search_placeholder': '140+ Länder & Visumtypen durchsuchen...',
      'take_photo': 'Biometrisches Passbild aufnehmen',
      'import_gallery': 'Aus Galerie importieren',
      'camera_studio': 'Kamera-Studio',
      'baby_mode': 'Baby- & Kleinkind-Modus',
      'baby_mode_desc': 'Erleichterte ICAO 9303 Vorgaben für Säuglinge',
      'compliance_inspection': 'Konformitäts-Prüfung',
      'biometric_compliant': 'Biometrisch Konform',
      'original_shot': 'Originalaufnahme',
      'background_presets': 'Hintergrund-Farben',
      'matting_cleanse': 'Freistellungs-Intensität',
      'balanced': 'Standard',
      'deep_cleanse': 'Tiefenreinigung (Wandschatten)',
      'auto_enhance': 'Automatische Belichtungsoptimierung',
      'brightness': 'Helligkeit',
      'contrast': 'Kontrast',
      'export_sheet': '10×15 cm Fotobogen drucken',
      'export_single': 'Einzelbild für Online-Portale',
      'export_pdf': 'Druckfertiges PDF (A4 & 10×15 cm)',
      'dm_guide_title': 'Bei dm / Rossmann für ca. 0,27 € drucken',
      'dm_guide_step1': '1. Am dm-Fototerminal: "Foto sofort drucken" ➔ 10×15 cm wählen.',
      'dm_guide_step2': '2. NICHT "Passfoto" (7,95 €) wählen! Standard-Abzug kostet ~0,27 €.',
      'dm_guide_step3': '3. "Ohne Rand" (100% Skalierung) aktivieren. An Schnittlinien schneiden.',
      'family_sheet_title': 'Familien-Kombibogen',
      'family_sheet_desc': 'Mehrere Familienmitglieder auf einem 10×15 cm Bogen drucken',
    },
  };

  static String get(String key, String lang) {
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
